### ISSUE TITLE
The pretrained weights is of models is on Food101 or FakeAVCeleb?

### ISSUE THREAD

**Issue by akankshasingh25** [Vincent-ZHQ/MRDF#4]
> For direct inference on Food101, we provide the pretrained checkpoint example [here](https://drive.google.com/drive/folders/1WdfkPRlzX-3Y4xSSS7F9WrR_Hdqpdudw?usp=sharing). The related dataset [splits](https://drive.google.com/drive/folders/1JOo_uA0vmHZaKj3LB6QG55THXkYRClhG?usp=drive_link) are also available

Is this a typo? @Vincent-ZHQ

**Comment by Vincent-ZHQ** [comment]
Thank you for your pointing out. Yes. It is a typo. I used the template from my other project. It should be a checkpoint for FakeAVCeleb.
